In [1]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

Mounted at /content/drive

In [27]:
restaurant_path = '/content/drive/MyDrive/DS5500 Capstone/yelp_academic_dataset_business.json'
review_path = '/content/drive/MyDrive/DS5500 Capstone/yelp_academic_dataset_review.json'
user_path = '/content/drive/MyDrive/DS5500 Capstone/yelp_academic_dataset_user.json'

In [3]:
restaurant_df = pd.read_json(restaurant_path, lines = True)
review_df = pd.read_json(review_path, lines = True)
user_df = pd.read_json(user_path, lines = True)

In [4]:
restaurant_df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [5]:
my_state = 'CA'
restaurant_ids = set(restaurant_df[restaurant_df['state'] == my_state]['business_id'])

In [17]:
CA_Restaurants = restaurant_df[restaurant_df['state'] == my_state]

In [28]:
CA_Restaurants = CA_Restaurants.reset_index(drop=True)
CA_Restaurants.to_csv("/content/drive/MyDrive/DS5500 Capstone/CA_Restaurants.csv")

In [6]:
review_df.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [7]:
user_ids = set(review_df[review_df['business_id'].isin(restaurant_ids)]['user_id'])

In [35]:
user_df[user_df['user_id'].isin(user_ids)].reset_index(drop=True).to_csv("/content/drive/MyDrive/DS5500 Capstone/CA_Users.csv")

In [8]:
#Rows are user ids
#Columns are restaurant ids

relevant_reviews_df = review_df[review_df['business_id'].isin(restaurant_ids)]

In [9]:
relevant_reviews_df.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
8,ZKvDG2sBvHVdF5oBNUOpAQ,wSTuiTk-sKNdcFyprzZAjg,B5XSoSG3SfvQGtKEGQ1tSQ,3,1,1,0,This easter instead of going to Lopez Lake we ...,2016-03-30 22:46:33
9,pUycOfUwM8vqX7KjRRhUEA,59MxRhNVhU9MYndMkz0wtw,gebiRewfieSdtt17PTW6Zg,3,0,0,0,Had a party of 6 here for hibachi. Our waitres...,2016-07-25 07:31:06
23,eCiWBf1CJ0Zdv1uVarEhhw,OhECKhQEexFypOMY6kypRw,vC2qm1y3Au5czBtbhc-DNw,4,0,0,0,"Yes, this is the only sushi place in town. How...",2013-09-04 03:48:20
31,YbMyvlDA2W3Py5lTz8VK-A,4hBhtCSgoxkrFgHa4YAD-w,bbEXAEFr4RYHLlZ-HFssTA,5,0,0,0,"Great burgers,fries and salad! Burgers have a...",2017-01-02 03:17:34
35,L0jv8c2FbpWSlfNC6bbUEA,bFPdtzu11Oi0f92EAcjqmg,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,What a great addition to the Funk Zone! Grab ...,2016-10-13 22:50:47

In [32]:
relevant_reviews_df.reset_index(drop=True).to_csv("/content/drive/MyDrive/DS5500 Capstone/CA_Reviews.csv")

In [10]:
review_matrix = relevant_reviews_df.pivot_table(index='user_id', columns='business_id', values='stars', aggfunc='first', fill_value=0)

In [11]:
from scipy.sparse import csr_matrix

sparse_review_matrix = csr_matrix(review_matrix.values)

In [12]:
len(review_matrix.columns)

5203

In [13]:
!pip install implicit
from scipy.sparse import csr_matrix
from implicit import als
import numpy as np


# 2. Train ALS model
model = als.AlternatingLeastSquares(
    factors=50,        # latent dimensions
    regularization=0.1,
    iterations=20,
    use_gpu=True
)
model.fit(sparse_review_matrix)

# 3. Get recommendations for a user
user_idx = 0  # index into your matrix
ids, scores = model.recommend(
    user_idx,
    sparse_review_matrix[user_idx],
    N=10                    # top 10 recommendations
    #filter_already_liked=True
)

# Map indices back to restaurant ids
recommended = review_matrix.columns[ids]

Collecting implicit
  Downloading implicit-0.7.2.tar.gz (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from implicit) (2.0.2)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.12/dist-packages (from implicit) (1.16.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from implicit) (4.67.3)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.12/dist-packages (from implicit) (3.6.0)
Building wheels for collected packages: implicit
  Building wheel for implicit (pyproject.toml) ... done
  Created wheel for implicit: filename=implicit-0.7.2-cp312-cp312-linux_x86_64.whl size=10906301 sha256=4920e5408188bc05efdffee2ff91e2fe2dd61a599c08a0e9ffa220de71dc4dd2
  Stored in directory: /root/.cache/pip/wheels/b2/00/4f/9ff8af07a0a53ac6007ea5d739da19cfe147a2df542b6899f8
Successfully built implicit
Installing collected packages: implicit
Successfully installed implicit-0.7.2

  0%|          | 0/20 [00:00<?, ?it/s]

In [14]:
list(recommended)

['iMTjejk6apJKzCukZnDw5A',
 'r2IhvKZQ_wLR5mLBnPOilg',
 'H-1qpp_77KggOAr9htUrEw',
 'l-rGtJt0E7PAklT0IK7oFQ',
 'S3QHy1sshUeZwXOYviVsXQ',
 'b5hxsRw76UUXcotxlCipuQ',
 'wFES5bGDiPANW13hNHnXOQ',
 'VOcGcN0bvGU_nzxbJgR5jQ',
 'cAbdvzqtFLaAAMFIyPf2AA',
 'Qkg16mN-8QR66gjzg6gMyw']

In [15]:
restaurant_df[restaurant_df['business_id'].isin(list(recommended))]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
5721,H-1qpp_77KggOAr9htUrEw,Cava Restaurant & Bar,1212 Coast Village Rd,Montecito,CA,93108,34.421378,-119.644135,4.0,367,0,"{'HasTV': 'True', 'GoodForKids': 'True', 'Rest...","Tapas Bars, Nightlife, Spanish, Latin American...","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'..."
8679,wFES5bGDiPANW13hNHnXOQ,Sakana Sushi Bar & Japanese,"1046 Coast Village Rd, Ste K",Santa Barbara,CA,93108,34.422264,-119.650288,4.0,374,1,"{'RestaurantsGoodForGroups': 'False', 'Busines...","Sushi Bars, Japanese, Restaurants","{'Tuesday': '17:0-21:30', 'Wednesday': '17:0-2..."
12105,S3QHy1sshUeZwXOYviVsXQ,Tre Lune,1151 Coast Village Rd,Montecito,CA,93108,34.420938,-119.646244,4.0,262,1,"{'WiFi': 'u'no'', 'RestaurantsDelivery': 'True...","Food, Italian, Restaurants","{'Monday': '11:30-21:0', 'Tuesday': '11:30-21:..."
43820,cAbdvzqtFLaAAMFIyPf2AA,Holdren's Steaks & Seafood,512 State St,Santa Barbara,CA,93101,34.417114,-119.695856,4.0,544,1,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","Steakhouses, Burgers, Bars, Seafood, Cocktail ...","{'Monday': '16:0-21:0', 'Tuesday': '16:0-21:0'..."
117868,VOcGcN0bvGU_nzxbJgR5jQ,Bettina,1014 Coast Village Rd,Santa Barbara,CA,93108,34.422562,-119.651716,4.5,311,1,"{'HappyHour': 'True', 'WiFi': 'u'free'', 'Rest...","Restaurants, Italian, Pizza","{'Monday': '0:0-0:0', 'Tuesday': '16:0-20:30',..."
120988,b5hxsRw76UUXcotxlCipuQ,Los Arroyos Mexican Restaurant & Take Out,1280 Coast Village Rd,Montecito,CA,93108,34.421762,-119.641328,3.5,353,1,"{'RestaurantsPriceRange2': '2', 'OutdoorSeatin...","Mexican, Coffee & Tea, Food, Cocktail Bars, Ni...","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
124421,iMTjejk6apJKzCukZnDw5A,Jeannine's Bakery & Restaurant,1253 Coast Village Rd,Montecito,CA,93108,34.421043,-119.642190,4.5,650,1,"{'NoiseLevel': 'u'average'', 'WiFi': 'u'no'', ...","American (Traditional), Coffee & Tea, Breakfas...","{'Monday': '0:0-0:0', 'Tuesday': '7:30-13:30',..."
138710,l-rGtJt0E7PAklT0IK7oFQ,Four Seasons Resort The Biltmore Santa Barbara,1260 Channel Drive,Santa Barbara,CA,93108,34.417339,-119.642040,4.5,508,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Hotels & Travel, Hotels, Event Planning & Serv...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
147785,Qkg16mN-8QR66gjzg6gMyw,Convivo Restaurant and Bar,901 E Cabrillo Blvd,Santa Barbara,CA,93103,34.417321,-119.672226,4.0,445,1,"{'BusinessAcceptsBitcoin': 'False', 'DogsAllow...","Bars, Mediterranean, Restaurants, Nightlife, M...","{'Monday': '7:0-21:0', 'Tuesday': '7:0-21:0', ..."
148705,r2IhvKZQ_wLR5mLBnPOilg,The Honor Bar,"1255 Coast Village Rd, Ste 101",Santa Barbara,CA,93108,34.421044,-119.641903,4.5,557,1,"{'BusinessAcceptsCreditCards': 'True', 'DogsAl...","Restaurants, Sandwiches, Nightlife, Bars, Amer...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ..."

In [36]:
CA_Restaurants

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,noByYNtDLQAra9ccqxdfDw,H&M,827-833 State St,Santa Barbara,CA,93101,34.420209,-119.700460,3.0,24,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Women's Clothing, Accessories, Children's Clot...","{'Monday': '11:0-18:0', 'Tuesday': '11:0-18:0'..."
2,IDtLPgUrqorrpqSLdfMhZQ,Helena Avenue Bakery,"131 Anacapa St, Ste C",Santa Barbara,CA,93101,34.414445,-119.690672,4.0,389,1,"{'RestaurantsTakeOut': 'True', 'NoiseLevel': '...","Food, Restaurants, Salad, Coffee & Tea, Breakf...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-14:0', '..."
3,nUqrF-h9S7myCcvNDecOvw,Iron Horse Auto Body,825 Cacique St,Santa Barbara,CA,93103,34.419620,-119.677032,4.5,32,1,"{'BusinessAcceptsCreditCards': 'True', 'WiFi':...","Towing, Automotive, Body Shops","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '..."
4,bYjnX_J1bHZob10DoSFkqQ,Tinkle Belle Diaper Service,,Santa Barbara,CA,93101,34.420334,-119.710749,5.0,17,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Parenting Classes, Maternity Wear, Fashion, Ed...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-18:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5198,Bo-GGwQNcLVwyKeYkbfAYg,Vino Divino,2012 De La Vina St,Santa Barbara,CA,93105,34.429154,-119.717222,5.0,19,1,"{'BusinessParking': '{'garage': False, 'street...","Event Planning & Services, Wine Tasting Room, ...","{'Monday': '0:0-0:0', 'Tuesday': '12:0-18:0', ..."
5199,8BUr8GviR2o_b-brO21wwQ,Kyle's Isla Vista,900 Embarcadero Del Mar,Isla Vista,CA,93117,34.412966,-119.856886,2.5,12,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsBit...","Restaurants, Burgers, Food, Ice Cream & Frozen...",None
5200,f7rTfTv6dwO-ovKhz-Rvgw,"Joanne & Tem Gronquist, OD","1805 State St, Ste B",Santa Barbara,CA,93101,34.428995,-119.712718,4.5,15,1,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Shopping, Eyewear & Opticians, Health & Medica...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '..."
5201,uriD7RFuHhLJeDdKaf0nFA,Pizza Guru,3534 State St,Santa Barbara,CA,93105,34.440689,-119.739681,4.0,299,0,"{'NoiseLevel': 'u'average'', 'RestaurantsGoodF...","Restaurants, Pizza, Food","{'Monday': '15:0-21:0', 'Tuesday': '15:0-21:0'..."
5202,JhSByBTYY1rGstRy76YmLA,Reiki with Darren,,Santa Barbara,CA,93105,34.420831,-119.698190,5.0,7,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Health & Medical, Supernatural Readings, Hospi...","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'..."